# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-08 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('image', models.CharField(max_length=255)),
                ('shortDescription', models.CharField(max_length=500)),
            ],
        ),
    ]
